services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: "redis:alpine"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"

